services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"  # Expose backend on port 5000
    environment:
      FLASK_APP: app:create_app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: production
      DATABASE_URL: ${DATABASE_URL}  # External database connection
      OPENAI_API_KEY: ${OPENAI_API_KEY}  # Azure OpenAI API key

    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VUE_APP_API_URL: http://127.0.0.1:5000 #http://backend:5000 #http://50xxxxx79:5000  # Use public IP for external access
    ports:
      - "80:80"  # Expose frontend on port 80
    environment:
      NODE_ENV: production
      VUE_APP_API_URL: http://127.0.0.1:5000 #http://backend:5000 #http://50xxxxxxx9:5000  # Use public IP to connect to backend
    networks:
      - app-network

  
  postgres:
    build:
      context: ./postgres-init
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ma0349
      POSTGRES_PASSWORD: MA0349_2025
      POSTGRES_DB: competency_assessment
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
